import { StyleSheet, Dimensions } from "react-native"
import { Colors } from "../../constants/Colors"

const { width } = Dimensions.get("window")

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.primary,
  },
  blueHeader: {
    backgroundColor: Colors.light.primary,
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  headerTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  logoContainer: {
    width: 45,
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 25,
  },
  logoImage: {
    width: 50,
    height: 50,
    resizeMode: "contain",
  },
  notificationButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  addressContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  addressTextContainer: {
    flex: 1,
    marginLeft: 8,
    marginRight: 4,
  },
  addressLabel: {
    fontSize: 9,
    color: "rgba(255, 255, 255, 0.75)",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  addressText: {
    fontSize: 13,
    color: "#FFFFFF",
    fontWeight: "700",
    marginTop: 1,
  },
  notificationBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    backgroundColor: Colors.light.secondary,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    borderWidth: 2,
    borderColor: Colors.light.primary,
  },
  notificationBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    paddingHorizontal: 14,
    height: 40,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: "#1A1A1A",
    fontWeight: "500",
  },
  whiteContent: {
    flex: 1,
    backgroundColor: Colors.light.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  scrollContent: {
    paddingTop: 16,
    paddingBottom: 120,
  },
  statsContainer: {
    paddingHorizontal: 12,
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: "rgba(139, 92, 246, 0.35)",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1.5,
    borderColor: "rgba(139, 92, 246, 0.15)",
    opacity: 0.6,
  },

  statCardActive: {
    backgroundColor: "#4F46E5",
    shadowColor: "#4F46E5",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 0,
    borderColor: "transparent",
    opacity: 1,
  },
  statCardInactive: {
    opacity: 0.6,
  },
  orderBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  orderBadgeActive: {
    backgroundColor: "#FFFFFF",
  },
  orderBadgeText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#8B5CF6",
  },
  orderBadgeTextActive: {
    color: "#4F46E5",
  },
  orderCardText: {
    flex: 1,
    fontSize: 17,
    fontWeight: "600",
    color: "#6B7280",
    marginLeft: 14,
    marginRight: 14,
  },
  orderCardTextActive: {
    color: "#FFFFFF",
  },
  statCardInactiveContent: {
    alignItems: "center",
    justifyContent: "center",
  },
  statLabelInactive: {
    fontSize: 18,
    fontWeight: "700",
    color: "#6B7280",
    marginTop: 10,
    textAlign: "center",
  },
  statCardCart: {
    backgroundColor: "rgba(20, 184, 166, 0.15)",
  },
  statCardCartActive: {
    backgroundColor: "#14B8A6",
    shadowColor: "#14B8A6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  statIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(139, 92, 246, 0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    borderWidth: 1,
    borderColor: "rgba(139, 92, 246, 0.2)",
  },
  statIconContainerActive: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    borderWidth: 0,
    borderColor: "transparent",
  },
  statIconContainerCartInactive: {
    backgroundColor: "rgba(20, 184, 166, 0.2)",
  },
  statIconContainerCart: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    shadowRadius: 10,
    elevation: 6,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: "900",
    color: "#8B5CF6",
    letterSpacing: -0.5,
  },
  statNumberActive: {
    color: "#FFFFFF",
  },
  statNumberCart: {
    color: "#14B8A6",
  },
  statNumberCartActive: {
    color: "#FFFFFF",
  },
  statLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#020202ff",
    flex: 1,
    lineHeight: 20,
  },
  statLabelActive: {
    color: "#FFFFFF",
    fontSize: 16,
  },
  statSubtitle: {
    fontSize: 12,
    fontWeight: "500",
    color: "#9CA3AF",
    marginTop: 2,
  },
  statSubtitleActive: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 13,
  },
  statLabelCart: {
    color: "#14B8A6",
  },
  statLabelCartActive: {
    color: "#FFFFFF",
  },
  statTextInactive: {
    color: "#9CA3AF",
  },
  section: {
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: Colors.light.text,
    letterSpacing: -0.5,
  },
  orgGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 16,
    gap: 12,
  },
  orgCard: {
    width: (width - 44) / 2,
    backgroundColor: Colors.light.surface,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    marginBottom: 4,
  },
  orgCardBackground: {
    width: "100%",
    height: 180,
  },
  orgCardBackgroundImage: {
    borderRadius: 16,
  },
  orgCardOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    padding: 12,
  },
  orgLogo: {
    width: 70,
    height: 70,
    borderRadius: 35,
    marginBottom: 10,
    borderWidth: 3,
    borderColor: "#FFFFFF",
  },
  orgNameWithImage: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    lineHeight: 18,
    textShadowColor: "rgba(0, 0, 0, 0.75)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  orgIconContainer: {
    alignItems: "center",
    padding: 20,
    minHeight: 180,
    justifyContent: "center",
  },
  orgIcon: {
    width: 80,
    height: 80,
    borderRadius: 45,
    backgroundColor: Colors.light.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Colors.light.border,
    marginBottom: 14,
  },
  orgLogoIcon: {
    width: 80,
    height:80,
    borderRadius: 45,
    marginBottom: 14,
    borderWidth: 2,
    borderColor: Colors.light.border,
  },
  orgName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
    textAlign: "center",
    lineHeight: 18,
  },
  loadingContainer: {
    paddingVertical: 80,
    alignItems: "center",
  },
  emptyState: {
    paddingVertical: 80,
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.light.text,
    marginTop: 16,
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 14,
    color: Colors.light.icon,
    textAlign: "center",
  },
  activeOrderBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: "#4A5EE8",
  },
  activeOrderIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#4A5EE8",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  activeOrderContent: {
    flex: 1,
  },
  activeOrderTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#333",
    marginBottom: 4,
  },
  activeOrderSubtitle: {
    fontSize: 14,
    color: "#666",
  },
  floatingOrderButton: {
    position: "absolute",
    bottom: 30,
    left: 20,
    right: 20,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#4A5EE8",
    borderRadius: 50,
    paddingVertical: 16,
    paddingHorizontal: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  floatingOrderIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  floatingOrderContent: {
    flex: 1,
  },
  floatingOrderTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 2,
  },
  floatingOrderSubtitle: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.85)",
  },
  cartButton: {
    position: "absolute",
    bottom: 100,
    left: 20,
    right: 20,
    backgroundColor: "#14B8A6",
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#14B8A6",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 10,
    zIndex: 1000,
    borderWidth: 2,
    borderColor: "#0D9488",
  },
  cartBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  cartBadgeText: {
    fontSize: 13,
    fontWeight: "900",
    color: "#14B8A6",
  },
  cartButtonText: {
    flex: 1,
    fontSize: 17,
    fontWeight: "800",
    color: "#FFFFFF",
    marginLeft: 14,
    letterSpacing: 0.2,
  },
})
