import { StyleSheet } from "react-native"
import { Colors } from "../../constants/Colors"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  header: {
    alignItems: "center",
    marginBottom: 48,
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  logoImage: {
    width: 140,
    height: 140,
    resizeMode: "contain",
  },
  appName: {
    fontSize: 38,
    fontWeight: "900",
    color: "#1A1A1A",
    marginBottom: 2,
    letterSpacing: -1.5,
    textAlign: "center",
  },
  tagline: {
    fontSize: 13,
    color: "#666666",
    fontWeight: "600",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    textAlign: "center",
  },
  formContainer: {
    width: "100%",
    paddingHorizontal: 0,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1A1A1A",
    marginBottom: 8,
    letterSpacing: -1,
    textAlign: "left",
  },
  subtitle: {
    fontSize: 15,
    color: "#888888",
    marginBottom: 32,
    fontWeight: "500",
    textAlign: "left",
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  inputContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2A2A2A",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  helperText: {
    fontSize: 12,
    marginTop: 6,
    fontWeight: "500",
    color: "#999999",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F8F8",
    borderRadius: 14,
    borderWidth: 2,
    borderColor: "#E8E8E8",
    paddingHorizontal: 16,
    height: 56,
  },
  inputIcon: {
    marginRight: 12,
    opacity: 0.6,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: "#1A1A1A",
    fontWeight: "500",
  },
  passwordInput: {
    paddingRight: 40,
  },
  eyeIcon: {
    position: "absolute",
    right: 16,
    padding: 4,
  },
  loginButton: {
    backgroundColor: "#14B8A6",
    borderRadius: 14,
    height: 56,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    marginBottom: 24,
    shadowColor: "#14B8A6",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  loginButtonDisabled: {
    opacity: 0.6,
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  linksContainer: {
    alignItems: "center",
    gap: 12,
    marginTop: 8,
  },
  link: {
    fontSize: 14,
    color: "#666666",
    textAlign: "center",
    fontWeight: "500",
  },
  linkAccent: {
    color: "#14B8A6",
    fontWeight: "700",
  },
  applyLink: {
    marginTop: 8,
  },
  linkAlt: {
    fontSize: 14,
    color: "#666666",
    textAlign: "center",
    lineHeight: 20,
    fontWeight: "500",
  },
  dividerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#E8E8E8",
  },
  dividerText: {
    marginHorizontal: 12,
    fontSize: 12,
    color: "#999999",
    fontWeight: "600",
    letterSpacing: 0.3,
  },
})
