import { StyleSheet, Dimensions } from "react-native"
import { Colors } from "../../constants/Colors"

const { width } = Dimensions.get("window")
const cardWidth = (width - 48) / 2 // 2 columns with 16px padding on each side and 16px gap

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.light.primary,
  },
  blueHeader: {
    backgroundColor: Colors.light.primary,
    paddingTop: 50,
    paddingBottom: 24,
    paddingHorizontal: 16,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  headerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  headerButtons: {
    flexDirection: "row",
    gap: 12,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  searchContainer: {
    backgroundColor: "transparent",
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 16,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    paddingHorizontal: 16,
    height: 45,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#000",
  },
  orgSection: {
    alignItems: "center",
    paddingBottom: 8,
  },
  orgIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 2.5,
    borderColor: "rgba(255, 255, 255, 0.5)",
  },
  orgName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
    letterSpacing: 0.3,
  },
  orgHeaderContainer: {
    height: 240,
    position: "relative",
  },
  orgHeaderImage: {
    width: "100%",
    height: "100%",
    position: "absolute",
  },
  headerGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 240,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    zIndex: 0,
  },
  headerOverlay: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 16,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 3,
  },
  orgInfoOverlay: {
    position: "absolute",
    bottom: 35,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 2,
  },
  orgLogoContainer: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 5,
    borderColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
    marginBottom: 12,
  },
  orgLogoImage: {
    width: "100%",
    height: "100%",
  },
  orgLogoImageNoHeader: {
    width: "100%",
    height: "100%",
    borderRadius: 32,
  },
  orgNameOnHeader: {
    fontSize: 24,
    fontWeight: "800",
    color: "#FFFFFF",
    textAlign: "center",
    letterSpacing: 0.5,
    textShadowColor: "rgba(0, 0, 0, 0.4)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  whiteContent: {
    flex: 1,
    backgroundColor: "#F8F9FA",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -17,
    paddingTop: 24,
    zIndex: 5,
  },
  vendorGrid: {
    padding: 16,
    paddingBottom: 40,
  },
  vendorGridWithHeader: {
    paddingTop: 100,
  },
  vendorRow: {
    justifyContent: "space-between",
    marginBottom: 16,
  },
  vendorCard: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    marginBottom: 16,
  },
  vendorImageContainer: {
    width: "100%",
    height: 180,
    position: "relative",
  },
  vendorImage: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F5F7FF",
  },
  vendorImagePlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#F5F7FF",
    alignItems: "center",
    justifyContent: "center",
  },
  statusBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#10B981",
    marginRight: 4,
  },
  statusText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#10B981",
  },
  vendorInfo: {
    padding: 12,
  },
  vendorName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 6,
    lineHeight: 20,
  },
  vendorAddress: {
    fontSize: 13,
    color: "#666",
    marginBottom: 8,
  },
  vendorMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  vendorArrow: {
    justifyContent: "center",
    paddingRight: 12,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1A1A1A",
    marginLeft: 4,
  },
  reviewCount: {
    fontSize: 12,
    fontWeight: "500",
    color: "#888",
    marginLeft: 3,
  },
  deliveryInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  deliveryTime: {
    fontSize: 12,
    color: "#666",
    marginLeft: 4,
    fontWeight: "500",
  },
  metaDivider: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#CCC",
    marginHorizontal: 7,
  },
  metaText: {
    fontSize: 12,
    color: "#666",
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  loadingContainerWithHeader: {
    paddingTop: 140,
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateWithHeader: {
    paddingTop: 140,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
    marginTop: 16,
    marginBottom: 4,
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  section: {
    marginBottom: 16,
  },
  sectionHeader: {
    paddingHorizontal: 16,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  sectionIcon: {
    marginRight: 12,
  },
  sectionTextContainer: {
    flexDirection: "column",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000",
  },
  sectionSubtitle: {
    fontSize: 12,
    color: "#666",
    marginTop: 2,
  },
  horizontalScroll: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  foodCard: {
    width: 150,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginRight: 12,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  foodImageContainer: {
    width: "100%",
    height: 115,
    backgroundColor: "#F5F7FF",
    position: "relative",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    overflow: "hidden",
  },
  foodImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  imageOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "25%",
    backgroundColor: "rgba(0, 0, 0, 0.03)",
  },
  foodImagePlaceholder: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5F7FF",
  },
  popularBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FF6B6B",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },
  recommendedBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#FFB800",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 4,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#FFFFFF",
    marginLeft: 3,
  },
  badgeTextSmall: {
    fontSize: 9,
    fontWeight: "700",
    color: "#FFFFFF",
    marginLeft: 2,
  },
  foodCardContent: {
    paddingHorizontal: 8,
    paddingTop: 5,
    paddingBottom: 6,
  },
  foodName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#000",
    marginBottom: 1,
    lineHeight: 14,
  },
  foodVendor: {
    fontSize: 9,
    color: "#666",
    marginBottom: 3,
  },
  foodFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  foodPrice: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000",
  },
  addButtonSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.light.secondary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.light.secondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  vendorGridInline: {
    paddingHorizontal: 16,
  },
  vendorCardWrapper: {
    marginBottom: 0,
  },
  cartButton: {
    position: "absolute",
    bottom: 24,
    left: 24,
    right: 24,
    backgroundColor: Colors.light.secondary,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  cartBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.light.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  cartBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.light.primary,
  },
  cartButtonText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    marginLeft: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "85%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 10,
  },
  modalClose: {
    position: "absolute",
    top: 16,
    right: 16,
    zIndex: 10,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  modalImageContainer: {
    width: "100%",
    height: 300,
    position: "relative",
  },
  modalImage: {
    width: "100%",
    height: "100%",
  },
  modalPlaceholder: {
    width: "100%",
    height: "100%",
    backgroundColor: "#FFF4CC",
    alignItems: "center",
    justifyContent: "center",
  },
  modalBody: {
    padding: 24,
    paddingTop: 20,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: Colors.light.text,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  modalVendor: {
    fontSize: 14,
    color: "#999",
    marginBottom: 12,
    fontWeight: "500",
  },
  modalDescription: {
    fontSize: 15,
    color: "#666",
    lineHeight: 22,
    marginBottom: 24,
  },
  quantitySection: {
    marginBottom: 28,
    backgroundColor: "#F8F9FA",
    padding: 16,
    borderRadius: 16,
  },
  quantityLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.light.text,
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
  },
  quantityButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  quantityValue: {
    fontSize: 22,
    fontWeight: "800",
    color: Colors.light.text,
    marginHorizontal: 28,
    minWidth: 30,
    textAlign: "center",
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
  },
  priceLabel: {
    fontSize: 13,
    color: "#999",
    marginBottom: 4,
    fontWeight: "500",
  },
  modalPrice: {
    fontSize: 28,
    fontWeight: "800",
    color: Colors.light.primary,
  },
  addToCartButton: {
    flexDirection: "row",
    backgroundColor: Colors.light.primary,
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: Colors.light.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  addToCartText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
})
