import { StyleSheet, Dimensions } from "react-native"

const { width } = Dimensions.get("window")

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#4A5EE8",
  },
  blueHeader: {
    backgroundColor: "#4A5EE8",
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  searchBar: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    paddingHorizontal: 16,
    height: 45,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: "#000",
  },
  whiteContent: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -20,
    paddingTop: 24,
  },
  orgBanner: {
    alignItems: "center",
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  orgImageContainer: {
    marginBottom: 12,
  },
  orgImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#F5F7FF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#4A5EE8",
  },
  orgName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#000",
    textAlign: "center",
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#000",
    paddingHorizontal: 20,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: "#666",
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  vendorList: {
    paddingHorizontal: 20,
    paddingVertical: 8,
  },
  vendorCircle: {
    alignItems: "center",
    marginRight: 20,
    width: 70,
  },
  circleIcon: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#F5F7FF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "#E8EBFF",
    overflow: "hidden",
  },
  circleImage: {
    width: "100%",
    height: "100%",
    borderRadius: 35,
  },
  circleName: {
    fontSize: 12,
    fontWeight: "600",
    color: "#000",
    textAlign: "center",
  },
  popularGrid: {
    flexDirection: "row",
    paddingHorizontal: 20,
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  popularCard: {
    width: (width - 52) / 3,
    marginBottom: 16,
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    padding: 8,
    alignItems: "center",
  },
  popularImagePlaceholder: {
    width: "100%",
    aspectRatio: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  popularTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#000",
    textAlign: "center",
    marginBottom: 2,
  },
  popularSubtitle: {
    fontSize: 10,
    color: "#666",
    textAlign: "center",
    marginBottom: 4,
  },
  popularPrice: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4A5EE8",
  },
  promoBanner: {
    marginHorizontal: 20,
    backgroundColor: "#E8F0FF",
    borderRadius: 16,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  promoContent: {
    flex: 1,
  },
  promoTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000",
    marginBottom: 4,
  },
  promoSubtitle: {
    fontSize: 14,
    color: "#666",
  },
  promoImage: {
    width: 60,
    height: 60,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 12,
  },
  loadingContainer: {
    paddingVertical: 40,
    alignItems: "center",
  },
  emptyState: {
    paddingVertical: 40,
    alignItems: "center",
  },
  emptyText: {
    fontSize: 16,
    color: "#666",
  },
})
